apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - pdb.yaml
  - storage-class.yaml

secretGenerator:
  - name: banking-secrets
    envs:
      - secret.env
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/part-of: banking
      app.kubernetes.io/managed-by: kustomize
