apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: banking
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app: redis
