apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-staging

resources:
  - ../../base
  - ingress.yaml

replicas:
  - name: banking-api
    count: 2
  - name: postgres
    count: 1
  - name: redis
    count: 1

images:
  - name: banking-api
    newTag: staging

patches:
  - path: app-patch.yaml
    target:
      kind: Deployment
      name: banking-api
  - target:
      kind: Namespace
      name: banking
    patch: |-
      - op: replace
        path: /metadata/name
        value: banking-staging

labels:
  - pairs:
      environment: staging
